Chore: Dev container proposal
WLAN-Pi/wlanpi-core pull request #58
Opened 2024-10-29 15:11 UTC by crvallance

## Type of change 

*Pick at least one.*

- [x] New feature (non-breaking change adding functionality)
- [x] Code quality improvement (refactor, performance improvements)

## Breaking change

*Does this Pull Request introduce a breaking change?* 

 No

## Proposed change

This addresses issue #57 by creating a [devcontainer](https://containers.dev/) environment which leverages a container backend. The container has all the OS level requirements as well as a systemd instance (not typical in a docker container) to allow for proper operation. As this is just a proposed change, no additional developer documentation has been added yet, however all the intent and operation is contained in the devcontainer.json and Containerfile. Once this is provisionally accepted I can flesh out usage docs for the contributor/developer sections.

## Testing

Testing was done manually. I was able to verify that all pre-requisites were installed, the "developing" step in [WORKFLOW.md](https://github.com/WLAN-Pi/wlanpi-core/blob/main/WORKFLOW.md#developing) correctly launches the server, and that I could pull a basic page. My environment uses VSCode and Docker Desktop. It has not been tested with other container wrappers like podman desktop or rancher desktop.

## Checklist

- [x] I have read the [contribution guidelines and policies](https://github.com/WLAN-Pi/.github/blob/main/docs/contributing.md)
- [x] I have targeted this PR against the correct git branch
- [x] I ran the test suite and verified it succeeded
- [x] I linked an approved GitHub issue to this PR (in the next section). No PR without a related GH issue. Conversations about your PR efforts in other channels such as electronic mail, social media, morse code, and WLAN Pi Slack **do not count**.
- [x] I have updated the changelog (if applicable)
- [x] I have added or updated the documentation (if applicable)

## Related Issues/PRs

- This PR is related to issue #57

2024-10-30 02:03 UTC, joshschmelzle commented
Since we're tied at the hip with the system python, can you target python3.9 instead of python3.11 for the time being? We're going to still be supporting Bullseye (py3.9) for some period of overlap after we migrate to Bookworm (py3.11).

2024-10-31 00:55 UTC, joshschmelzle requested changes
Requesting change from py3.11 to py3.9.

2024-10-31 00:55 UTC, joshschmelzle commented on .devcontainer/Containerfile
> +  sudo python3.11 python3.11-venv python-is-python3 python3.11-dev git ssh build-essential
Since we're tied at the hip with the system python (dh-virtualenv), can you target python3.9 instead of python3.11 for the time being? We're going to still be supporting Bullseye (py3.9) for some period of overlap even after we migrate to Bookworm (py3.11).

2024-11-07 03:13 UTC, crvallance commented on .devcontainer/Containerfile
> +  sudo python3.11 python3.11-venv python-is-python3 python3.11-dev git ssh build-essential
@joshschmelzle I added 3.9 via deadsnakes and used update-alternatives to prioritize 3.9 over the OS default of 3.10. Let me know if there's any other changes you'd like to see.

2024-11-07 13:14 UTC, joshschmelzle commented on .devcontainer/Containerfile
> +  sudo python3.11 python3.11-venv python-is-python3 python3.11-dev git ssh build-essential
Appears 3.10 is still being set as the python version with a higher priority than 3.9.

<img width="1326" alt="image" src="https://github.com/user-attachments/assets/16c0336b-10e9-452d-9f03-6498eda8c0c3">

2024-11-08 00:21 UTC, crvallance commented on .devcontainer/Containerfile
> +  sudo python3.11 python3.11-venv python-is-python3 python3.11-dev git ssh build-essential
Whoops... mistook weight for order. Swapped out now.

2024-11-08 00:48 UTC, merged